Models/MilestoneChain.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace MVCApplicationToDo.Models
{
    public class MilestoneChain
    {
        public int Id { get; set; }

        [DisplayName("Código")] 
        [StringLength(5)] 
        public required string Code { get; set; }

        [DisplayName("Descrição")]
        [StringLength(255)]
        public required string Title { get; set; }
        public int ProjectId { get; set; }
        public Project? Project { get; set; } = null;
        public List<Milestone>? Milestones { get; set; } = new List<Milestone>();
        public ICollection<TaskItem>? TaskItems { get; set; }
    }
}

Controllers/MilestoneChainsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCApplicationToDo.Data;
using MVCApplicationToDo.Models;

namespace MVCApplicationToDo.Controllers
{
    public class MilestoneChainsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MilestoneChainsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: MilestoneChains
        public async Task<IActionResult> Index()
        {
            var selectedProjectId = HttpContext.Session.GetInt32("SelectedProjectId");
            var selectedProjectTitle = HttpContext.Session.GetString("SelectedProjectTitle");

            ViewBag.SelectedProjectId = selectedProjectId;
            ViewBag.SelectedProjectTitle = selectedProjectTitle;

            var milestoneChains = await _context.MilestoneChains
                .Where(m => m.ProjectId == selectedProjectId)
                .ToListAsync();

            return View(milestoneChains);
        }

        // GET: MilestoneChains/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var milestoneChain = await _context.MilestoneChains
                .Include(m => m.Milestones)
                .ThenInclude(m => m.MilestoneItem)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (milestoneChain == null)
            {
                return NotFound();
            }

            return View(milestoneChain);
        }

        // GET: MilestoneChains/Create
        public async Task<IActionResult> Create(int? stepCount)
        {
            var selectedProjectId = HttpContext.Session.GetInt32("SelectedProjectId");
            var selectedProjectTitle = HttpContext.Session.GetString("SelectedProjectTitle");
            ViewBag.SelectedProjectId = selectedProjectId;
            ViewBag.SelectedProjectTitle = selectedProjectTitle;

            if (selectedProjectId == null)
            {
                return RedirectToAction("Index", "Projects"); // Redirecionar caso não haja um projeto selecionado
            }


            var milestoneItems = await _context.MilestoneItems
                .Where(m => m.ProjectId == selectedProjectId)
                .ToListAsync();

            ViewBag.MilestoneItems = new SelectList(milestoneItems, "Id", "Code");

            // Se o stepCount não for passado, use um valor padrão (1)
            int count = stepCount ?? 1;

            // Gere os milestones dinamicamente
            var milestoneChain = new MilestoneChain
            {
                Code = "MC01",
                Title = "Nova Cadeia de Marcos",
                Milestones = Enumerable.Range(1, count).Select(i => new Milestone
                {
                    Code = $"MS0{i}",
                    Title = $"Milestone {i}",
                    Value = 0,
                    Order = i
                }).ToList()
            };

            return View(milestoneChain);


        }

        // POST: MilestoneChains/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Code,Title,Milestones")] MilestoneChain milestoneChain)
        {
            var selectedProjectId = HttpContext.Session.GetInt32("SelectedProjectId");
            ViewBag.SelectedProjectId = selectedProjectId;

            if (selectedProjectId == null)
            {
                return RedirectToAction("Index", "Projects"); // Redirecionar caso não haja projeto selecionado
            }

            var mscode = _context.MilestoneChains
                .Where(m => m.Code == milestoneChain.Code)
                .FirstOrDefault();
            if (mscode != null)
            {
                ModelState.AddModelError("Code", "Já existe uma cadeia de marcos com esse código.");
            }

                if (ModelState.IsValid)
            {
                try
                {
                    milestoneChain.ProjectId = selectedProjectId.Value;
                    _context.MilestoneChains.Add(milestoneChain);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateException ex)
                {
                    ModelState.AddModelError("", $"Erro ao salvar os dados: {ex.Message}");
                }
            }

            var milestoneItems = await _context.MilestoneItems
                .Where(m => m.ProjectId == selectedProjectId)
                .ToListAsync();

            ViewBag.MilestoneItems = new SelectList(milestoneItems, "Id", "Code");
            return View(milestoneChain);
        }

        // GET: MilestoneChains/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var milestoneChain = await _context.MilestoneChains
                .Include(m => m.Milestones)
                .FirstOrDefaultAsync(m => m.Id == id);

            var milestoneItems = await _context.MilestoneItems
                .Where(m => m.ProjectId == milestoneChain.ProjectId)
                .ToListAsync();

            ViewBag.MilestoneItems = new SelectList(milestoneItems, "Id", "Code");

            if (milestoneChain == null)
            {
                return NotFound();
            }
            return View(milestoneChain);
        }

        // POST: MilestoneChains/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Code,Title,Milestones")] MilestoneChain milestoneChain)
        {
            if (id != milestoneChain.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var existingMilestoneChain = await _context.MilestoneChains
                        .Include(m => m.Milestones)
                        .FirstOrDefaultAsync(m => m.Id == id);

                    if (existingMilestoneChain == null)
                    {
                        return NotFound();
                    }

                    // Atualize as propriedades da MilestoneChain
                    existingMilestoneChain.Code = milestoneChain.Code;
                    existingMilestoneChain.Title = milestoneChain.Title;

                    // Atualize os Milestones
                    foreach (var milestone in milestoneChain.Milestones)
                    {
                        var existingMilestone = existingMilestoneChain.Milestones
                            .FirstOrDefault(m => m.Id == milestone.Id);

                        if (existingMilestone != null)
                        {
                            existingMilestone.MilestoneItemId = milestone.MilestoneItemId;
                            existingMilestone.Value = milestone.Value;
                        }
                        else
                        {
                            existingMilestoneChain.Milestones.Add(milestone);
                        }
                    }

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MilestoneChainExists(milestoneChain.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(milestoneChain);
        }


        // GET: MilestoneChains/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var milestoneChain = await _context.MilestoneChains
                .FirstOrDefaultAsync(m => m.Id == id);
            if (milestoneChain == null)
            {
                return NotFound();
            }

            return View(milestoneChain);
        }

        // POST: MilestoneChains/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var milestoneChain = await _context.MilestoneChains.FindAsync(id);
            if (milestoneChain != null)
            {
                _context.MilestoneChains.Remove(milestoneChain);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MilestoneChainExists(int id)
        {
            return _context.MilestoneChains.Any(e => e.Id == id);
        }
    }
}

Controllers/MilestonesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCApplicationToDo.Data;
using MVCApplicationToDo.Models;

namespace MVCApplicationToDo.Controllers
{
    public class MilestonesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MilestonesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Milestones
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Milestones.Include(m => m.MilestoneChain);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Milestones/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var milestone = await _context.Milestones
                .Include(m => m.MilestoneChain)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (milestone == null)
            {
                return NotFound();
            }

            return View(milestone);
        }

        // GET: Milestones/Create
        public IActionResult Create()
        {
            ViewData["MilestoneChainId"] = new SelectList(_context.MilestoneChains, "Id", "Title");
            return View();
        }

        // POST: Milestones/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Code,Title,Value,Order,MilestoneChainId")] Milestone milestone)
        {
            if (ModelState.IsValid)
            {
                _context.Add(milestone);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MilestoneChainId"] = new SelectList(_context.MilestoneChains, "Id", "Title", milestone.MilestoneChainId);
            return View(milestone);
        }

        // GET: Milestones/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var milestone = await _context.Milestones.FindAsync(id);
            if (milestone == null)
            {
                return NotFound();
            }
            ViewData["MilestoneChainId"] = new SelectList(_context.MilestoneChains, "Id", "Title", milestone.MilestoneChainId);
            return View(milestone);
        }

        // POST: Milestones/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Code,Title,Value,Order,MilestoneChainId")] Milestone milestone)
        {
            if (id != milestone.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(milestone);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MilestoneExists(milestone.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MilestoneChainId"] = new SelectList(_context.MilestoneChains, "Id", "Title", milestone.MilestoneChainId);
            return View(milestone);
        }

        // GET: Milestones/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var milestone = await _context.Milestones
                .Include(m => m.MilestoneChain)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (milestone == null)
            {
                return NotFound();
            }

            return View(milestone);
        }

        // POST: Milestones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var milestone = await _context.Milestones.FindAsync(id);
            if (milestone != null)
            {
                _context.Milestones.Remove(milestone);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MilestoneExists(int id)
        {
            return _context.Milestones.Any(e => e.Id == id);
        }
    }
}

Views/MilestoneChains/Create.cshtml
@model MVCApplicationToDo.Models.MilestoneChain

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Milestone Chain</h4>

@if (ViewBag.SelectedProjectId != null && ViewBag.SelectedProjectTitle != null)
{
    <div class="container">
        <p>Projeto Selecionado: @ViewBag.SelectedProjectTitle</p>
    </div>
}
<form asp-action="Create" method="get">
    <div class="form-group col-3">
        <table>
            <tr>
                <td>
                    <input type="number" id="stepsInput" name="stepCount" class="form-control" placeholder="Número de steps" min="1" required />
                </td>
                <td>
                    <button type="submit" class="btn btn-primary">Adicionar</button>
                </td>
            </tr>
        </table>
    </div>
</form>

<hr />
<h5>Detalhes</h5>

<form asp-action="Create" method="post" class="row">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group col-md-2">
            <label asp-for="Code" class="control-label"></label>
            <input asp-for="Code" class="form-control"/>
            <span asp-validation-for="Code" class="text-danger"></span>
        </div>
    <div class="form-group col-md-6" style="margin-bottom: 30px;">
            <label asp-for="Title" class="control-label"></label>
            <input asp-for="Title" class="form-control"/>
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <br />
    <h5>Milestones Chain</h5>

    <div class="col-3">
        <table class="table col-md-2">
            <thead>
                <tr>
                    <th class="col-md-1 text-center">Step</th>
                    <th class="col-md-1 text-center">Progresso</th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.Milestones.Count; i++)
                {
                    <tr>
                        <td class="col-md-2">
                            <div class="form-group">
                                <input type="hidden" name="Milestones[@i].Id" value="@Model.Milestones[i].Id" />
                                <input type="hidden" name="Milestones[@i].Order" value="@i" />
                                <select asp-for="Milestones[@i].MilestoneItemId" class="form-control small-select" asp-items="ViewBag.MilestoneItems">
                                    <option value="">Select</option>
                                </select>
                            </div>
                        </td>
                        <td class="col-md-1">
                            <div class="form-group">
                                <input type="number" name="Milestones[@i].Value" value="@Model.Milestones[i].Value" class="form-control" />
                                <span asp-validation-for="Milestones[@i].Value" class="text-danger"></span>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>
<br />
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/MilestoneChains/Delete.cshtml
@model MVCApplicationToDo.Models.MilestoneChain

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MilestoneChain</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Code)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Code)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/MilestoneChains/Details.cshtml
@model MVCApplicationToDo.Models.MilestoneChain

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>MilestoneChain</h4>
    <hr />
    <br />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Code)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Code)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
    </dl>
    <br />
    <h3>Steps</h3>
    <table class="table col-md-2">
        <thead>
            <tr>
                <th class="col-md-1">Code</th>
                <th class="col-md-1">Title</th>
                <th class="col-md-1">Progresso</th>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.Milestones.Count; i++)
            {
                <tr>
                    <td class="col-md-3">
                        @Html.DisplayFor(model => model.Milestones[i].MilestoneItem.Code)
                    </td>
                    <td class="col-md-3">
                        @Html.DisplayFor(model => model.Milestones[i].MilestoneItem.Title)
                    </td>
                    <td class="col-md-3">
                        @Html.DisplayFor(model => model.Milestones[i].Value)
                    </td>
                </tr>
            }
        </tbody>
        </table>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-controller="Milestones" asp-action="Create">Add Milestones</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/MilestoneChains/Edit.cshtml
@model MVCApplicationToDo.Models.MilestoneChain

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>MilestoneChain</h4>
<hr />
<form asp-action="Edit" method="post" class="row">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
    <div class="form-group col-md-2">
        <label asp-for="Code" class="control-label"></label>
        @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
        <span asp-validation-for="Code" class="text-danger"></span>
    </div>
    <div class="form-group col-md-6">
        <label asp-for="Title" class="control-label"></label>
        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="form-group col-md-6">
        <br />
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
    
    <table class="table col-md-6">
        <thead>
            <tr>
                <th class="col-md-1 text-center">Step</th>
                <th class="col-md-6 text-center">Valor</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Milestones != null && Model.Milestones.Count > 0)
            {
                for (int i = 0; i < Model.Milestones.Count; i++)
                {
                    <tr>
                        <td class="col-md-2">
                            <div class="form-group">
                                <input type="hidden" name="Milestones[@i].Id" value="@Model.Milestones[i].Id" />
                                <input type="hidden" name="Milestones[@i].Order" value="@i" />
                                <select asp-for="Milestones[@i].MilestoneItemId" class="form-control small-select" asp-items="ViewBag.MilestoneItems">
                                    <option value="">Select</option>
                                </select>
                            </div>
                        </td>
                        <td class="col-md-1">
                            <div class="form-group">
                                <input type="number" name="Milestones[@i].Value" value="@Model.Milestones[i].Value" class="form-control" />
                            </div>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="3" class="text-center">
                        Nenhum milestone disponível.
                    </td>
                </tr>
            }
        </tbody>
    </table>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/MilestoneChains/Index.cshtml
@model IEnumerable<MVCApplicationToDo.Models.MilestoneChain>

@{
    ViewData["Title"] = "Index";
}

<h1>Milestone Chains Index</h1>

@if (ViewBag.SelectedProjectId != null && ViewBag.SelectedProjectTitle != null)
{
    <div class="container">
        <p>Projeto Selecionado: @ViewBag.SelectedProjectTitle</p>
    </div>
}

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>